name: Run Minecraft Bot

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 * * * *' # roda a cada hora

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código
        uses: actions/checkout@v3

      - name: Instalar Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      - name: Rodar bot
        run: node index.js